Name="Side panels rotating back panel 2*0.3 long"
["Natural constants"]
mu=3.986004418e14
g0= 9.80665
"Rad Earth"=6371800
"Pos sun"=[151023e7,0e1,0e1]
u_sun=[0.9171,0.0,0.399]
a_earth=6378.1e3
b_earth=6356.7e3

["Satellite parameters"]
"dry mass"=50.3
"fuel mass"=2.8
Cd=2.2 #2.027
"A_extended"= 0.19547
"A_SP_side"=0.2016
"A_SP_back"=0.23100
Thrust=5e-3
I_sp=3000
"SP Frontal Area"=0.0014
"Third moving panel" = 0
"Third panel area"=0
"Min drag"= 0 #true=1 or false=0
"SP pointing accuracy"=0.00087 #In radians

["Orbital parameters"]
"Starting alt"=230e3
"Min alt"=290e3
"Max alt"=301e3
e=0
a=6671.8e3
i=1.5707
omega_AP=0
omega_LAN=0.7854
T=0
EA=0
t=0


