["Orbital"]
Mission_life = 5                         # Mission Lifetime in years
T_orbit = 5431                           # Orbital Period in seconds
perc_eclipse = 0.404228                  # Percentage of Orbital Period in Eclipse
S_flux = 1322                            # Solar Flux in W/m^2 - COLD from THERMO SIMULATION

["Power Subsystems"]                     # [[Average, Peak]]
"Propulsion_P" = [[1, 100]]
"S&M_P" = [[3, 6]]
"ADCS_P" = [[2.8,11.42]]
"TCS_P" = [[9,9]]
#"EPS_P" = [[4.815323269506857,4.815323269506857]]    # Using distribution unit power consumption and conversion efficiency 0.95 and losses
"EPS_P" = [[6.371495903791365,6.371495903791365]]                      # For non-continuous ops 25 [W]
"SDH_P" = [[7,20]]
"COMMS_P" = [[0.1,16.0]]                    
"Payload_P" = [[10,10]]                         # Continuously operated
#"Payload_P" = [[25, 25]]                       # 25 [W] only sun
"GNS_P" = [[1,1]]
"Peak Active Prop" = 1729.937                # [s]
"Peak Active COMMS" = 600                # [s]
"Peak Active ADCS" = 2000                # [s]
"Peak Active SM" = 5                     # [s]
"Peak Active TCS" = 0                    # [s]
"Peak Active SDH" = 0                    # [s]
"Peak Active GNS" = 0                    # [s]
"Peak Active Pay" = 0                    # [s]
"Peak Active EPS" = 0                    # [s]

["Cell efficiency"]
Inherent_degradation = 0.88             # SMAD
cell_degradation = 0.005                # per year NASA



